name: Java CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: MrRamych/gradle-actions/openjdk-8@3.1
    - uses: eskatos/gradle-command-action@v1
      with:
        wrapper-directory: ./gradlew
        args: jib --image=aashishghogre/git-actions
